# language: node_js
# node_js:
#   - lts/*
# script:
#   - bash ./deploy.sh
# deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: docs/.vuepress/dist
#   github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
#   keep-history: true
#   on:
#     branch: master
sudo: required
language: node_js
node_js: stable
script: bash ./deploy.sh
branches:
  only:
  - master
notifications:
  email: false